# Generated by Django 4.2 on 2026-06-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Amazing')])),
                ('energy_level', models.IntegerField()),
                ('emotion_tag', models.CharField(blank=True, choices=[('anxious', 'Anxious'), ('grateful', 'Grateful'), ('calm', 'Calm'), ('sad', 'Sad'), ('happy', 'Happy'), ('angry', 'Angry'), ('excited', 'Excited'), ('tired', 'Tired')], max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
