# Generated by Django 4.2 on 2026-06-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('prompt_text', models.TextField()),
                ('is_seasonal', models.BooleanField(default=False)),
                ('season_theme', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('mood_score', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='journal_voice/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('prompt_category', models.CharField(blank=True, choices=[('gratitude', 'Gratitude'), ('reflection', 'Reflection'), ('growth', 'Growth'), ('anxiety_release', 'Anxiety Release')], max_length=20)),
                ('prompt_used', models.TextField(blank=True)),
                ('is_guided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
