# Generated by Django 4.2 on 2026-06-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('custom', 'Custom Days')], default='daily', max_length=20)),
                ('custom_days', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, choices=[('sleep', 'Sleep'), ('movement', 'Movement'), ('mindfulness', 'Mindfulness'), ('nutrition', 'Nutrition'), ('social', 'Social')], max_length=20)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('goal_duration', models.IntegerField(blank=True, null=True)),
                ('goal_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completion', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('skipped', 'Skipped')], default='full', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habittracker.habit')),
            ],
        ),
    ]
