# Generated by Django 4.2 on 2026-06-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sound_type', models.CharField(choices=[('nature', 'Nature'), ('binaural', 'Binaural Tones')], max_length=20)),
                ('binaural_type', models.CharField(blank=True, choices=[('focus', 'Focus'), ('sleep', 'Sleep'), ('calm', 'Calm')], max_length=20)),
                ('audio_file', models.FileField(upload_to='ambient_sounds/')),
            ],
        ),
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breathing_type', models.CharField(choices=[('box', 'Box Breathing (4-4-4-4)'), ('478', '4-7-8 Calming Breath'), ('custom', 'Custom')], max_length=20)),
                ('inhale_duration', models.IntegerField(default=4)),
                ('hold_duration', models.IntegerField(default=4)),
                ('exhale_duration', models.IntegerField(default=4)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmbientMixSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_timer_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sounds', models.ManyToManyField(to='mindfulness.ambientsound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
